import { parseAbi } from "viem";

// Exact frontend surface from contracts/src/TrancheVault.sol on main.
export const trancheVaultAbi = parseAbi([
  "function phase() view returns (uint8)",
  "function quote() view returns (address)",
  "function risky() view returns (address)",
  "function senior() view returns (address)",
  "function junior() view returns (address)",
  "function curator() view returns (address)",
  "function positionVenue() view returns (address)",
  "function oracle() view returns (address)",
  "function aqua() view returns (address)",
  "function bufferStrategy() view returns (address)",
  "function bufferApp() view returns (address)",
  "function bufferShipped() view returns (bool)",
  "function shippedQuote() view returns (uint256)",
  "function nav() view returns (uint256)",
  "function seniorClaim() view returns (uint256)",
  "function coverageWad() view returns (int256)",
  "function juniorShareWad() view returns (uint256)",
  "function terms() view returns (uint256 seniorPrincipal, uint256 juniorPrincipal, uint256 couponWad, uint256 feeSplitWad, uint64 start, uint64 duration)",
  "function seniorPot() view returns (uint256)",
  "function juniorPot() view returns (uint256)",
  "function unwindCost() view returns (uint256)",
  "function rebalanceCost() view returns (uint256)",
  "function rebalanceCount() view returns (uint32)",
  "function lastRebalanceAt() view returns (uint64)",
  "function unwindDeadline() view returns (uint64)",
  "function navAtSettlement() view returns (uint256)",
  "function seniorClaimAtSettlement() view returns (uint256)",
  "function seniorSupplyAtSettlement() view returns (uint256)",
  "function juniorSupplyAtSettlement() view returns (uint256)",
  "function depositSenior(uint256 assets)",
  "function depositJunior(uint256 assets)",
  "function redeemSenior(uint256 shares) returns (uint256 assets)",
  "function redeemJunior(uint256 shares) returns (uint256 assets)",
  "event Deposited(address indexed who, bool indexed isSenior, uint256 assets)",
  "event Activated(uint256 seniorPrincipal, uint256 juniorPrincipal, uint256 juniorShareWad, uint256 feeSplitWad, uint256 shipped)",
  "event BufferCalled(address indexed caller, int256 coverageWad, uint256 shippedQuote)",
  "event Rebalanced(address indexed curator, uint256 cost, uint256 cumulativeCost)",
  "event Liquidated(address indexed caller, uint256 riskySold, uint256 quoteReceived)",
  "event Donated(address indexed who, uint256 assets)",
  "event SettlementBegun(uint256 navBeforeUnwind, uint256 quoteReturned, uint256 unwindCost, uint64 unwindDeadline)",
  "event Settled(uint256 nav, uint256 seniorClaim, uint256 seniorPot, uint256 juniorPot)",
  "event Cancelled(uint256 seniorPrincipal, uint256 juniorPrincipal)",
  "event Redeemed(address indexed who, bool indexed isSenior, uint256 shares, uint256 assets)",
]);

export const erc20Abi = parseAbi([
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function balanceOf(address owner) view returns (uint256)",
  "function totalSupply() view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
]);

export const positionVenueAbi = parseAbi([
  "function valueInQuote() view returns (uint256)",
  "function tickLower() view returns (int24)",
  "function tickUpper() view returns (int24)",
  "function liquidity() view returns (uint128)",
]);
